#ifndef DEFINE_ADDR_H_
#define DEFINE_ADDR_H_

#define ZERO_PAGE_START_ADDR 0x0
#define STACK_START_ADDR 0x1FF
#define RAM_START_ADDR 0x200
#define NMI_VECTOR 0xFFFA
#define RESET_VECTOR 0xFFFC
#define IRQ_VECTOR 0xFFFE

#endif // DEFINE_ADDR_H_
